library(shiny)

ui <- navbarPage("Elo Prediction Creator",
                 tabPanel("Data Import",
                          fluidRow(wellPanel(fileInput("games.csv", "Upload games .csv file",
                                                       accept = ".csv"))),
                          tableOutput("gamesRaw")),
                 tabPanel("Game Stats",
                          fluidRow(column(5, 
                                          wellPanel(withSpinner(tableOutput("teamList")), style = "overflow-x: scroll;"),
                                          tableOutput("winLossDrawTable")),
                                   column(7,
                                          withSpinner(plotlyOutput("MOVHistogram")), hr(),
                                          withSpinner(plotlyOutput("scoreHistogram")), hr(),
                                          withSpinner(plotlyOutput("homeAwayScorehistogram")), hr(),
                                          withSpinner(plotlyOutput("homeAwayMOVhistogram")), hr(),
                                          withSpinner(plotlyOutput("homeAwayWinPct"))))
                 ),
                 tabPanel("Elo Parameters",
                          fluidRow(column(3, uiOutput("eloParamsPanel"),
                                          textOutput("pctCorrect"),
                                          textOutput("overlapValue"),
                                          textOutput("residualScore"),
                                          textOutput("avgResidualScore"),
                                          downloadButton("downloadEloTable", "Download Results")),
                                   column(9, withSpinner(plotlyOutput("eloPlot", height = 800)),
                                          withSpinner(plotlyOutput("livePctCorrectPlot")),
                                          withSpinner(plotlyOutput("calibrationPlot")),
                                          withSpinner(plotlyOutput("calibrationResidualPlot")),
                                          withSpinner(plotlyOutput("calibrationScaledResidualPlot")),
                                          withSpinner(plotlyOutput("overlapPlot"))))
                 ),
                 tabPanel("Elo Optimization",
                          fluidRow(column(4, wellPanel(h3("Elo Optimization Ranges"), hr(),
                                                       actionButton("optimizeGo", "Optimize"),
                                                       checkboxInput("useOptimizedValues", "Use Optimzed Values in Elo Tab?"), hr(),
                                                       sliderInput("baseKRange", "Base K value", 10, 100, c(20,60)),
                                                       sliderInput("homeAdvantageRange", "Home Field Advantage", 0, 200, c(50,150), step = 10),
                                                       sliderInput("MOVmultiplierRange", "Margin of Victory Multiplier", 0, 3, c(0,2), step = 0.1),
                                                       sliderInput("pctRegressionRange", "Regression % to mean after season", 0, 100, c(0,60), step = 5),
                                                       h3("Optimization Parameters"),
                                                       numericInput("nIterations", "Number of Iterations", 5),
                                                       numericInput("topNmedian", "Number of Values to combine per iteration", 10),
                                                       sliderInput("ConvergenceFactor", "Convergence Multiplier", 0.1, 0.9, 0.5, step =0.05))),
                                   column(8, tabsetPanel(
                                     tabPanel("Optimization Plots",
                                              withSpinner(plotlyOutput("residualScorePLot")),
                                              withSpinner(plotlyOutput("HFARangePLot")),
                                              withSpinner(plotlyOutput("REGRangePLot")),
                                              withSpinner(plotlyOutput("KRangePLot")),
                                              withSpinner(plotlyOutput("MOVRangePLot"))),
                                     tabPanel("Optimized Parameters",
                                              tableOutput("optimizedValues"))
                                     )))),
                 tabPanel("Future Predictions",
                          fluidRow(wellPanel(fileInput("futureGames.csv", "Upload future games .csv file",
                                                       accept = ".csv"))),
                          tabsetPanel(tabPanel("Game Results",
                                               tableOutput("predictedGames")),
                                      tabPanel("Summary",
                                               tableOutput("summarisedPredictions")))),
                 tabPanel("Example Data",
                          downloadButton("downloadNFL2000.2020", "Download NFL Scores 2000-2020 (template for scores)"),
                          hr(),
                          downloadButton("downloadAUDL2014.2021", "Download AUDL Scores 2014-2021 (template for scores)"),
                          hr(),
                          downloadButton("downloadNFL2021", "Download NFL regular season 2021 schedule (prediction template)"),
                          hr(),
                          downloadButton("downloadAUDL2022", "Download AUDL regular season 2022 schedule (prediction template)"))
)