library(shiny)

ui <- navbarPage("Elo Prediction Creator",
                 tabPanel("Data Import",
                          fluidRow(wellPanel(fileInput("games.csv", "Upload games .csv file",
                                                       accept = ".csv"))),
                          tableOutput("gamesRaw")),
                 tabPanel("Game Stats",
                          fluidRow(column(5, 
                                          wellPanel(withSpinner(tableOutput("teamList")), style = "overflow-x: scroll;"),
                                          tableOutput("winLossDrawTable")),
                                   column(7,
                                          withSpinner(plotlyOutput("MOVHistogram")), hr(),
                                          withSpinner(plotlyOutput("scoreHistogram")), hr(),
                                          withSpinner(plotlyOutput("homeAwayScorehistogram")), hr(),
                                          withSpinner(plotlyOutput("homeAwayMOVhistogram")), hr(),
                                          withSpinner(plotlyOutput("homeAwayWinPct"))))
                 ),
                 tabPanel("Elo Parameters",
                          fluidRow(column(3, wellPanel(h3("Elo Equation Parameters"),
                                                       numericInput("startingElo", "Starting Elo Value", 1400),
                                                       numericInput("EloDenom", "Elo Denominator", 400),
                                                       numericInput("baseK", "Base K value", 30),
                                                       numericInput("homeAdvantage", "Home Field Advantage", 100),
                                                       numericInput("MOVmultiplier", "Margin of Victory Multiplier", 1),
                                                       numericInput("MOVinteger", "Margin of Victory Integer", 1),
                                                       numericInput("playoffMultiplier", "Playoff Importance Multiplier", 1.2), hr(),
                                                       h3("Other Factors"),
                                                       numericInput("pctRegression", "Regression % to mean after season", 20),
                                                       numericInput("pctNotToInclude", "% of initial games to leave out of accuracy calculation", 10),
                                                       h3("Scoring Metrics"),
                                                       sliderInput("weightCorrect", "Weight of Correct Outcome (vs MOV) in scoring", 0, 1, 0.5, step = 0.05)),
                                          textOutput("pctCorrect"),
                                          textOutput("overlapValue"),
                                          textOutput("percentileScore"),
                                          textOutput("weightedScore")),
                                   column(9, withSpinner(plotlyOutput("livePctCorrectPlot")),
                                          withSpinner(plotlyOutput("livePercentileScorePlot")),
                                          withSpinner(plotlyOutput("liveCombinedScorePlot")),
                                          withSpinner(plotlyOutput("calibrationPlot")),
                                          withSpinner(plotlyOutput("calibrationResidualPlot")),
                                          withSpinner(plotlyOutput("calibrationScaledResidualPlot")),
                                          withSpinner(plotlyOutput("percentileScoreDistributionPlot")),
                                          withSpinner(plotlyOutput("percentileScoreDensityPlot")),
                                          withSpinner(plotlyOutput("overlapPlot")),
                                          withSpinner(plotlyOutput("eloPlot", height = 800))))
                 ),
                 tabPanel("Elo Optimization",
                          fluidRow(column(4, wellPanel(h3("Elo Optimization Ranges"),
                                                       #sliderInput("startingEloRange", "Starting Elo Value", 1000, 2000, c(1200,1600)),
                                                       #sliderInput("EloDenomRange", "Elo Denominator", 200, 600, c(300,500)),
                                                       sliderInput("baseKRange", "Base K value", 10, 50, c(20,40)),
                                                       numericInput("baseKIter", "Base K iterator", 1), hr(),
                                                       sliderInput("homeAdvantageRange", "Home Field Advantage", 0, 200, c(50,150), step = 10),
                                                       numericInput("homeAdvantageIter", "Home Advantager Iterator", 10), hr(),
                                                       sliderInput("MOVmultiplierRange", "Margin of Victory Multiplier", 0, 3, c(0,2), step = 0.1),
                                                       numericInput("MOVmultiplierIter", "MOV iterator", 0.2, step = 0.1), hr(),
                                                       #sliderInput("MOVintegerRange", "Margin of Victory Integer", 0, 10, c(0,5)),
                                                       #sliderInput("playoffMultiplierRange", "Playoff Importance Multiplier", 0, 3, c(0, 2)),
                                                       sliderInput("pctRegressionRange", "Regression % to mean after season", 0, 100, c(0,60), step = 5),
                                                       numericInput("pctRegressionIter", "Regression % after season Iterator", 10))),
                                   column(8,withSpinner(plotlyOutput("optKPlot")),
                                          withSpinner(plotlyOutput("optHFAPlot")),
                                          withSpinner(plotlyOutput("optMOVmultPlot")),
                                          withSpinner(plotlyOutput("optPctRegPlot")))),
                 )       
)